
name: deploy-to-branch

on:
  push:
    branches: [ master ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        working-directory: .
        run: |
          npm ci
          CI=false npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: brakdag-build
          folder: ./build
